package com.sorted.commons.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ResponseCode {

	// @formatter:off
	SUCCESSFUL("SE_0000", "Successful.", "Successful."),
	ERR_0001("SE_0001", "Something went wrong.", "Something went wrong."),
	INVALID_REQ("SE_0002", "Invalid request.", "Invalid request."),
	MANDATE_CATEGORY("SE_0003", "Category name is mandatory.", "Category name is mandatory."),
	MANDATE_SUB_CATEGORY("SE_0004", "Sub category name is missing.", "Sub category name is missing."),
	INVALID_SUB_CATEGORY("SE_0005", "Invalid sub category.", "Invalid sub category."),
	INVALID_MIN_SUB_CATEGORY("SE_0006", "At least one value is required for sub category.",	"At least one value is required for sub category."),
	INVALID_SUB_CATEGORY_VAL("SE_0007", "Invalid sub category value.", "Invalid sub category value"),
	INVALID_CATEGORY_SELECTED("SE_0008", "Invalid category selected.", "Invalid category selected."),
	MISSING_PRODUCT_NAME("SE_0009", "Product name is missing.", "Product name is missing."),
	INVALID_PRODUCT_NAME("SE_0010", "Invalid product name.", "Invalid product name."),
	MISSING_PRODUCT_PRICE("SE_0011", "Price is missing.", "Price is missing."),
	INVALID_PRODUCT_MRP("SE_0012", "Invalid product MRP.", "Invalid product MRP."),
	MISSING_QUANTITY("SE_0013", "Quantity is missing.", "Quantity is missing."),
	INVALID_QUANTITY("SE_0014", "Invalid quantity.", "Invalid quantity."),
	CATEGORY_NOT_SELECTED("SE_0015", "Category not selected.", "Category not selected."),
	EMPTY_SUB_CATEGORY("SE_0016", "Select atleast 1 sub-category.", "Select atleast 1 sub-category."),
	EMPTY_ATTRIBUTE("SE_0017", "Attribute is missing.", "Attribute is missing."),
	INVALID_ATTRIBUTE("SE_0018", "Invalid attribute selected.", "Invalid attribute selected."),
	MISSING_PRODUCT_DESCRIPTION("SE_0019", "Product description is missing.", "Product description is missing."),
	INVALID_PRODUCT_DESCRIPTION("SE_0020", "Product description is invalid.", "Product description is invalid."),
	MISSING_ID("SE_0021", "Entity id is missing for update.", "Something went wrong."),
	NO_RECORD("SE_0022", "No record found.", "No record found."),
	NOT_A_LIST("SE_0023", "List is required.", "Something went wrong."),
	MISSING_USER_ID("SE_0024", "User id is missing.", "Requester details missing."),
	MISSING_ROLE_ID("SE_0025", "Role id is missing.", "Requester details missing."),
	MISSING_PRODUCT_ID("SE_0026", "Product id is missing.", "Product id is missing."),
	PRODUCT_NOT_FOUND("SE_0027", "Product not found.", "Product not found."),
	PRODUCT_OUT_OF_STOCK("SE_0026", "This product out of stock.", "This product out of stock."),
	STOCK_LIMIT_REACHED("SE_0029", "Stock limit reached. Additional quantities cannot be added at this time.", "Stock limit reached. Additional quantities cannot be added at this time."),
	MISSING_PRODUCT_QUANTITY("SE_0030", "Product quantity is missing.", "Product quantity is missing."),
	INVAALID_PRODUCT_QUANTITY("SE_0031", "Product quantity is invalid.", "Product quantity is invalid."),
	CART_NOT_FOUND("SE_0032", "First crete a cart for this user by adding an item.", "First crete a cart for this user by adding an item."),
	PASS_VALIDATION_FAILURE_1("SE_0033", "Password must contain atleast one lower case letter", "Password must contain atleast one lower case letter"),
	PASS_VALIDATION_FAILURE_2("SE_0034", "Password must contain atleast one upper case letter", "Password must contain atleast one upper case letter"),
	PASS_VALIDATION_FAILURE_3("SE_0035", "Password must contain atleast one numeric value", "Password must contain atleast one numeric value"),
	PASS_VALIDATION_FAILURE_4("SE_0036", "Password must contain atleast one special character", "Password must contain atleast one special character"),
	PASS_VALIDATION_FAILURE_5("SE_0037", "Password must contain minimum eight characters", "Password must contain minimum eight characters"),
	DUPLICATE_MOBILE("SE_0038", "An account is already created using this mobile no, login or use a different mobile no.", "An account is already created using this mobile no, login or use a different mobile no."),
	DUPLICATE_EMAIL("SE_0039", "This email id is linked to another mobile no.", "This email id is linked to another mobile no."),
	DEFAULT_ROLE_MISSING("SE_0040", "Default role not found.", "Something went wrong."),
	MISSING_OTP("SE_0041", "Please enter otp.", "Please enter otp."),
	INVALID_OTP("SE_0042", "Please enter a valid otp.", "Please enter a valid otp."),
	MISSING_ENTITY("SE_0043", "Entity id is missing.", "Something went wrong."),
	ENTITY_NOT_FOUND("SE_0044", "Entity not found.", "Something went wrong."),
	OTP_EXPIRED("SE_0045", "Otp expired.", "Otp expired."),
	MISSING_FN("SE_0044", "First name is missing.", "First name is missing."),
	MISSING_LN("SE_0045", "Last name is missing.", "Last name is missing."),
	MISSING_MN("SE_0046", "Mobile number is missing.", "Mobile number is missing."),
	MISSING_EI("SE_0047", "Email ID is missing.", "Email ID is missing."),
	MISSING_PASS("SE_0048", "Password is missing.", "Password is missing."),
	INVALID_FN("SE_0049", "Please enter a valid first name.", "Please enter a valid first name."),
	INVALID_LN("SE_0050", "Please enter a valid last name.", "Please enter a valid last name."),
	INVALID_MN("SE_0051", "Please enter a valid mobile number.", "Please enter a valid mobile number."),
	INVALID_EI("SE_0052", "Please enter a valid email ID.", "Please enter a valid first email ID."),
	MISSING_MOBILE("SE_0053", "Mobile no is missing.", "Mobile no is missing."),
	LOGIN_FAILED("SE_0054", "Invalid user name or password.", "Invalid user name or password."),
	USER_BLOCKED("SE_0055", "This account is blocked, please contact customer service.", "This account is blocked, please contact customer service."),
	ROLE_MISSING("SE_0056", "Role not found.", "Something went wrong."),
	USER_NOT_FOUND("SE_0057", "User Not found.", "User Not found."),
	INVALID_SEMISTER("SE_0058", "Invalid branch.", "Invalid semister selected."),
	INVALID_BRANCH("SE_0059", "Invalid branch.", "Branch not found."),
	ENTITY_DEFINATION_INCOMPLETE("SE_0060", "Entity defination missing in EntityDetails.", "Something went wrong."),
	ALREADY_SIGNED_UP("SE_0061", "This mobile no is already used, please sign in or use a different mobile no.", "This mobile no is already used, please sign in or use a different mobile no."),
	MISSING_REF_ID("SE_0062", "Reference id is missing.", "Reference id is missing."),
	MSSING_CUST_DEF_ROLE("SE_0063", "Customer default role not found.", "Something went wrong."),
	MISSING_PROCESS_TYPE("SE_0064", "Process type missing", "Something went wrong."),
	INVALID_RESEND_REQUEST("SE_0065", "No OTP found for resend process.", "Please go back and start the process again."),
	SESSION_EXPIRED("SE_0066", "Session expired.", "Session expired, please restart the process."),
	BR_OLD_PASSWORD("SE_0067", "Use a different password.", "Use a different password."),
	CATEGORY_NOT_FOUND("SE_0068", "Selected category not found.", "Selected category not found."),
	INVALID_CATEGORY("SE_0069", "Invalid category name.", "Invalid category name."),
	PLEASE_SELECT_SELLER("SE_0070", "Please select seller", "Please select seller"),
	SELLER_NOT_FOUND("SE_0071", "Seller not found", "Seller not found"),
	NO_ITEMS("SE_0072", "Items list is empty.", "Something went wrong."),
	MANDATE_MRP("SE_0075", "MRP is missing.", "MRP is missing."),
	MANDATE_SP("SE_0078", "Selling price is missing.", "Selling price is missing."),
	INVALID_SELLING_PRICE("SE_0079", "Invalid Selling Price.", "Invalid Selling Price."),
	ACCESS_DENIED("SE_0080", "Access Denied.", "Access Denied."),
	PROMT_SIGNUP("SE_0081", "Hold on! You need to log in or sign up to buy this. Join us—it's quick and easy!", "Hold on! You need to log in or sign up to buy this. Join us—it's quick and easy!"),
	CART_EMPTY("SE_0082", "Cart is empty, please add items.", "Cart is empty, please add items."),
	OUT_OF_STOCK("SE_0083", "Sorry! Your requested item ran out of stock.", "Sorry! Your requested item ran out of stock."),
	DELETED_PRODUCT("SE_0084", "Product might be deleted.", "Something went wrong."),
	FEW_OUT_OF_STOCK("SE_0085", "Oops! Few items jist went out of stock, please refresh and try again.", "Oops! Few items jist went out of stock, please refresh and try again."),
	MISSING_ADDRESS("SE_0086", "Address is missing.", "Address is missing."),
	MANDATE_STREET("SE_0087", "Street 1 is mandatory.", "Street 1 is mandatory."),
	INVALID_STREET("SE_0088", "Please provide valid Street 1.", "Please provide valid Street 1."),
	INVALID_STREET_2("SE_0089", "Please provide valid Street 2.", "Please provide valid Street 2."),
	MANDATE_LANDMARK("SE_0090", "Landmark is mandatory.", "Landmark is mandatory."),
	INVALID_LANDMARK("SE_0091", "Please provide valid Landmark.", "Please provide valid Landmark."),
	MANDATE_CITY("SE_0091", "City is mandatory.", "City is mandatory."),
	INVALID_CITY("SE_0092", "Please provide valid City.", "Please provide valid City."),
	MANDATE_STATE("SE_0093", "City is mandatory.", "City is mandatory."),
	INVALID_STATE("SE_0094", "Please provide valid City.", "Please provide valid City."),
	MANDATE_PINCODE("SE_0095", "Pincode is mandatory.", "Pincode is mandatory."),
	INVALID_PINCODE("SE_0096", "Please provide valid Pincode.", "Please provide valid Pincode."),
	MANDATE_ADDRESS_TYPE("SE_0097", "Please select address type.", "Please select address type."),
	MANDATE_OTHER_ADDRESS_DESC("SE_0098", "Please input other address type description.", "Please input other address type description."),
	INVALID_OTHER_ADDRESS_DESC("SE_0099", "Invalid other address type description.", "Invalid input other address type description."),
	MANDATE_CUST_USER_ID("SE_0100", "Customer user id is missing.", "Customer user id is missing."),
	VARIENT_NOT_FOUND("SE_0101", "Varient does not exists.", "Varient does not exists."),
	DUPLICATE_VARIENT("SE_0102", "Varient already exists with this name.", "Varient already exists with this name."),
	INVALID_VARIENT_NAME("SE_0103", "Invalid varient name.", "Invalid varient name."),
	ITEM_NOT_FOUND("SE_0073", "Item not found.", "Something went wrong.");
	// @formatter:on

	private final String code;
	private final String errorMessage;
	private final String userMessage;
}
