name: Publish Package to GitHub Packages

on:
  push:
    branches: [ library ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true
        env:
          SE_ENV: prod
          SPRING_PROFILES_ACTIVE: prod

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.SEBACKEND_ACCESS_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          SE_ENV: prod
          SPRING_PROFILES_ACTIVE: prod
